# Generated by Django 5.0.6 on 2024-05-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimaRedStar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
